### PR TITLE
Changed import for Python 3

### PR DESCRIPTION
**Pull request by gauss256**
A one-line change to fix an import issue in Python 3

### CODE REVIEW

**Comment by mpariente** [comment]
Thanks again!

**Comment by hagenw** [comment]
Would be great if you could make a new release of pystoi in order to include this fix with `pip install pystoi`.

**Comment by mpariente** [comment]
I just came back from holiday and wanted to do it today, it's done ! Tell me if you have any problem with it.

**Comment by hagenw** [comment]
Cool, thank you. It worked for me.
Maybe you can add also a tag that it appears on https://github.com/mpariente/pystoi/releases.

**Pull request merged**
