### PR TITLE
Vectorization

### PR DESCRIPTION
**Pull request by PrzemekPobrotyn**
As per contribution request, in this pull request we add vectorisation of a number of computations, specfically:
* Vectorization of nearly all of `utils.remove_silent_frames`
* Vectorization of computations in both classical and extended STOI

There are still a few for loops left in form of list comprehension, though.

As a result, we obtain a nearly 4-fold speed up in computations of classical STOI and 1.5-fold speed up in computations of extended STOI.

We also demonstrate that the results of vectorized implementation agree with the previous one, within tolerance. See documentation for `np.allclose` for details about tolerance threshold.

The minuscule differences in results are most likely due to numerical inaccuracies when performing matrix operations vs doing computations in loops.

See the images below for results and time comparisons.

screen shot 2018-07-18 at 9 27 13 am

screen shot 2018-07-18 at 9 27 40 am

Before merging, please update the README file accordingly.
Thank you!

### CODE REVIEW

**Comment by mpariente** [comment]
Thanks a lot for your PR, it looks very nice !
I'll update the README and remove `corr` from the tests and then I'll merge it.

**Comment by mpariente** [comment]
Thanks again for your contribution, this 4x speed up is very valuable!

**Comment by mpariente** [comment]
It seems you are not added as a contributor, do you know why that is?

**Comment by PrzemekPobrotyn** [comment]
Hi,

Thanks for acting so quickly on my pull request and merging it! I’m glad I could help :) As for not appearing as a contributor, I think it might be because I didn’t put any GPG keys in my github account? I’ll try and fix it in the evening, I do want to appear in the contributors list! It’s my first ever pull request on github so I’m still learning how to do it properly!

Best,
Przemek

**Comment by mpariente** [comment]
Indeed, you need a GPG key so the commits will be linked to your profile.
If you want me to revert the merge so you can make a new PR which is exactly the same but linked to your profile, it's possible. I'm happy to make your first PR a success!

**Comment by PrzemekPobrotyn** [comment]
I'd also commited with the wrong e-mail address. I've now added the second email address to my account and added GPG keys associated with both email addresses linked to my github account. If you can revert the PR so that I can make it again and be listed as a contributor, I'd appreciate that! Apologies for the hassle.

**Comment by PrzemekPobrotyn** [comment]
It seems like reverting the changes was not necessary after all, looks like updating my e-mail was enough for my to appear in the list of contributors. Anyway, I submitted the same changes in new PR. Once again apologies for the mess.

**Pull request merged**
